#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f counter.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace lfsr4_challenge.sv --exe lfsr_tb_challenge.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlfsr4_challenge.mk Vlfsr4_challenge

# run executable simulation file
obj_dir/Vlfsr4_challenge
